import { Attendee } from "@/types/attendee";

export const ATTENDEES: Attendee[] = [
  {
    name: "Tony Wang",
    role: "新加坡城市联络人",
    email: "tongwang.zh@outlook.com",
    introduction: "SeeDAO新加坡城市联络人",
    wallet_address: "0x4B162DBa01943Bd8CD8af668bE72fB769999aC83",
  },
  {
    name: "Mia Qiu",
    role: "新人营",
    email: "jlzxwt8@126.com",
    introduction: "Help &amp; Grow社群发起人之一",
    wallet_address: "0x9f0a97311761d0560ae9496ec76f6b58c7970e3e",
  },
  {
    name: "Hermina Zhang",
    role: "SeeDAO 成员",
    email: "herminazhang@gmail.com",
    introduction: "Hashkey BD/Sales/IR",
    wallet_address: "0xC6c6CC4D20E6Ad4D0a484f5a3a413e471DbDa1cC",
  },
  {
    name: "Aaron Chan",
    role: "对SeeDAO感兴趣",
    email: "aaron.chan@okx.com",
    introduction: "看看有什么地方可以合作的",
  },
  {
    name: "Agnes",
    role: "对SeeDAO感兴趣",
    email: "wangwenjiaagnes@gmail.com",
    introduction: "n.a.",
  },
  {
    name: "Alex Young",
    role: "对SeeDAO感兴趣",
    email: "valorsobretodo@gmail.com",
    introduction: "挖矿",
  },
  {
    name: "Anna",
    role: "对SeeDAO感兴趣",
    email: "hongna07@gmail.com",
    introduction: "没有经验，对DAO感兴趣",
  },
  {
    name: "Chenghao Zhuang",
    role: "对SeeDAO感兴趣",
    email: "alinozhuang@outlook.com",
    introduction: "Gamefi 实习经历",
  },
  {
    name: "CHENG Ling",
    role: "对SeeDAO感兴趣",
    email: "cranesama@gmail.com",
    introduction: "Illicit Activities detection on Crypto-Transaction network",
  },
  {
    name: "Cipher ",
    role: "对SeeDAO感兴趣",
    email: "cipher@nervina.io",
    introduction: "治理",
    wallet_address: "0x67ebD60f4475ab8FA91a5a564CE73c6Dc67F477E",
  },
  {
    name: "Coral",
    role: "SeeDAO 成员",
    email: "614854275@qq.com",
    introduction: "无",
  },
  {
    name: "Darren",
    role: "SeeDAO 成员",
    email: "darrenonce@gmail.com",
    introduction: "Dao社区发展",
    wallet_address: "0x34E4e1194F6d2c71019B6eB02f0a629f14Aa213b",
  },
  {
    name: "Dorothy",
    role: "对SeeDAO感兴趣",
    email: "dorothy@altresear.ch",
    introduction: "Head of growth at altlayer. Ex snx and hashkey",
    wallet_address: "0x80dd72e4252f2d54Af2B131d9AB09Af24F893aE1",
  },
  {
    name: "Eddie",
    role: "对SeeDAO感兴趣",
    email: "eddie@chainup.com",
    introduction: "SeeDAO如何链接web3从业者，会为大家提供哪些便利？",
    wallet_address: "0x740528246511b5187ffeac9c68d3fec177924fc7",
  },
  {
    name: "Gao Yaning",
    role: "对SeeDAO感兴趣",
    email: "Andy.Gao@Sig.com",
    introduction: "VC investing in web3",
  },
  {
    name: "Gloria",
    role: "对SeeDAO感兴趣",
    email: "mengyagloriahe@gmail.com",
    introduction: "Currently working in Web3 and stablecoin infrastructure ",
    wallet_address: "0x57d2A2aD036887B90c1066AE0B87Af2C86818E46",
  },
  {
    name: "Iris",
    role: "SeeDAO 成员",
    email: "iris921426135@gmail.com",
    introduction: "Help&amp;Grow Member",
    wallet_address: "0x6769384718817AE4AAFE446C04265eEa9fcA1909",
  },
  {
    name: "Jeff",
    role: "对SeeDAO感兴趣",
    email: "ng310808@gmail.com",
    introduction: "Gamfi and connecting in data and earn",
    wallet_address: "0x34BFd5096b6f7CE079273B47e1A3Ee1895E07b6F",
  },
  {
    name: "Jeff Xu",
    role: "对SeeDAO感兴趣",
    email: "jeff_z_xu@yahoo.com",
    introduction: "有比较长的程序交易经验。尝试将交易平台移到 web3",
    wallet_address: "0x0b1339129FF643328dce586bf6E64039bFdE503b",
  },
  {
    name: "jinbin",
    role: "对SeeDAO感兴趣",
    email: "wzxiejinbin@me.com",
    introduction: "2013年开始入圈，创业，挖矿，投资，目前在火币投资部门",
  },
  {
    name: "jing",
    role: "对SeeDAO感兴趣",
    email: "liujingyun0626@126.com",
    introduction: "na",
  },
  {
    name: "joy",
    role: "对SeeDAO感兴趣",
    email: "joy543song@gmail.com",
    introduction: "bybit listing, 希望了解dao的治理",
    wallet_address: "0xE7C28aCc58A6D2d3993b102a7c0B4EB45FeEBeBc",
  },
  {
    name: "Kathy Zhu",
    role: "对SeeDAO感兴趣",
    email: "muse@ofr.asia",
    introduction:
      "18年入行，在币安做国际市场，现在在Old Fashion Research做投资",
    wallet_address: "Magicmuse.eth ",
  },
  {
    name: "Leon",
    role: "SeeDAO 成员",
    email: "lihaodong98@outlook.com",
    introduction: "元宇宙",
    wallet_address: "0x231C0E8229c109745e7415039735399Ac4f206A6",
  },
  {
    name: "Li Xiang",
    role: "SeeDAO 成员",
    email: "herrycodelee@gmail.com",
    introduction: "SeeDAO 里面的远程工作",
    wallet_address: "0xEA16AD632080c54276a4c2394021DaF75E2672e9",
  },
  {
    name: "Lulu Li",
    role: "对SeeDAO感兴趣",
    email: "lulu@didelidi.com",
    introduction: "I am NFT artist now exploring DAO for creators.",
  },
  {
    name: "Lynn",
    role: "SeeDAO 成员",
    email: "julielynn0915@gmail.com",
    introduction: "目前web3的从业者，SeeDAO成员",
    wallet_address: "0xecd86a1f45cd32d737f7b97c2c5000e0cc547c1a",
  },
  {
    name: "Ma Yan",
    role: "对SeeDAO感兴趣",
    email: "mymymyyan@163.com",
    introduction: "运营",
  },
  {
    name: "miaomiao",
    role: "对SeeDAO感兴趣",
    email: "1685222405@qq.com",
    introduction: "如何在web3挣钱",
  },
  {
    name: "norman",
    role: "对SeeDAO感兴趣",
    email: "info@metafrontier-blockchain.com",
    introduction: "Gamefi， Defi",
  },
  {
    name: "Queenie Chu",
    role: "对SeeDAO感兴趣",
    email: "chuqiao2022@gmail.com",
    introduction: "链上部署",
  },
  {
    name: "rami",
    role: "对SeeDAO感兴趣",
    email: "ramiguo@icloud.com",
    introduction: "了解打工人任何利用 DAO 挣钱",
  },
  {
    name: "Rochelle",
    role: "对SeeDAO感兴趣",
    email: "runxiao.lei@gmail.com",
    introduction: "AI",
  },
  {
    name: "Sarah",
    role: "对SeeDAO感兴趣",
    email: "sarahwuyz@gmail.com",
    introduction: "初步了解",
  },
  {
    name: "sensor",
    role: "对SeeDAO感兴趣",
    email: "fectrain@outlook.com",
    introduction: "对这个能做什么比较好奇",
  },
  {
    name: "shen zhu",
    role: "对SeeDAO感兴趣",
    email: "e0952415@u.nus.edu",
    introduction: "无",
  },
  {
    name: "Siqi CHEN",
    role: "对SeeDAO感兴趣",
    email: "siqi.chen@essec.edu",
    introduction:
      " I am excited about exploring the intersection of Web3 and digital marketing to help companies build sustainable and ethical brands that align with ESG principles. I believe that this emerging technology has the power to drive positive change and create a more equitable and transparent online world. With a strong background in problem-solving and data analysis, I am eager to apply my skills to this rapidly evolving industry and make a meaningful contribution to its growth. I am actively seeking internship opportunities to further develop my expertise in Web3 and ESG analysis, and I am committed to building a career that reflects my values and aspirations.",
  },
  {
    name: "TIAN JIAJIE",
    role: "对SeeDAO感兴趣",
    email: "1816402521@qq.com",
    introduction: "Metaveese",
  },
  {
    name: "wei li",
    role: "对SeeDAO感兴趣",
    email: "weili.walk@gmail.com",
    introduction: "dao",
    wallet_address: "beagles.eth",
  },
  {
    name: "Wenhui JIA",
    role: "对SeeDAO感兴趣",
    email: "b00798766@essec.edu",
    introduction: "Web3未来可能的发展空间，如何渗透各行业？",
  },
  {
    name: "wenshuang",
    role: "对SeeDAO感兴趣",
    email: "carajzr@gmail.com",
    introduction: "BuidlerDAO打杂，关注Social和NFT方向",
    wallet_address: "0x12189a3b33cda988ef10375ce835ab582d3248c3",
  },
  {
    name: "Wu yuanyang",
    role: "对SeeDAO感兴趣",
    email: "yuanyangwu@numencyber.com",
    introduction: "Security Audit",
  },
  {
    name: "Xifan",
    role: "对SeeDAO感兴趣",
    email: "wang1787@e.ntu.edu.sg",
    introduction: "之前参与过元宇宙与虚拟人的研究",
  },
  {
    name: "Xu Chenyang",
    role: "对SeeDAO感兴趣",
    email: "1355584278@qq.com",
    introduction: "元宇宙；如何进行商业应用",
  },
  {
    name: "Ye Qingxiang",
    role: "对SeeDAO感兴趣",
    email: "yeqingxiang@yahoo.com",
    introduction: "了解web3的最新发展",
  },
  {
    name: "Yihan Li",
    role: "对SeeDAO感兴趣",
    email: "neil.li.dev@gmail.com",
    introduction: "Web3 developer， 怎么通过seedao加速项目",
    wallet_address: "0x46dc3f7326288c1216be3b6BBccCE53d9AF18897",
  },
  {
    name: "Yishi ",
    role: "对SeeDAO感兴趣",
    email: "yi23468@gmail.com",
    introduction: "Shide ",
    wallet_address: "Shide ",
  },
  {
    name: "Yolanda",
    role: "对SeeDAO感兴趣",
    email: "Yozhang555@gmail.com",
    introduction: "Nope ",
  },
  {
    name: "Yolin",
    role: "对SeeDAO感兴趣",
    email: "yulin.tyl@alibaba-inc.com",
    introduction: "行业动态",
  },
  {
    name: "YouLin",
    role: "对SeeDAO感兴趣",
    email: "lynnnstark@gmail.com",
    introduction: "Metaverse",
  },
  {
    name: "Yue Hao",
    role: "对SeeDAO感兴趣",
    email: "hy1607492521@gmail.com",
    introduction: ".",
    wallet_address: "0x2ddF43Cf2ecaF8531d5d68C77982271fF7D97592",
  },
  {
    name: "YUE Yiran",
    role: "对SeeDAO感兴趣",
    email: "yueyiran3@qq.com",
    introduction: "-",
  },
  {
    name: "zoey",
    role: "对SeeDAO感兴趣",
    email: "zoeyzou221@gmail.com",
    introduction: "web3项目 ",
  },
  {
    name: "ZOU YUFAN",
    role: "对SeeDAO感兴趣",
    email: "zouyufan@outlook.com",
    introduction: "new to web3, 借此作为了解的切入口",
    wallet_address: "0x54483413677ad9f88510ab741b5d9f93059d2cbe",
  },
  {
    name: "寒胜 (Hanseong Choi)",
    role: "对SeeDAO感兴趣",
    email: "hanseong.choi@aol.com",
    introduction: "社群的维护",
  },
  {
    name: " Zhidong Zhang",
    role: "对SeeDAO感兴趣",
    email: "zhidong.zhang@pingcap.com",
    introduction: "Centralised database",
  },
  {
    name: "林达",
    role: "对SeeDAO感兴趣",
    email: "mumuda2333@gmail.com",
    introduction: "了解一下web3",
  },
];
